In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("zomato.csv")

In [3]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='str')

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  str
 1   address                      51717 non-null  str
 2   name                         51717 non-null  str
 3   online_order                 51717 non-null  str
 4   book_table                   51717 non-null  str
 5   rate                         43942 non-null  str
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  str
 8   location                     51696 non-null  str
 9   rest_type                    51490 non-null  str
 10  dish_liked                   23639 non-null  str
 11  cuisines                     51672 non-null  str
 12  approx_cost(for two people)  51371 non-null  str
 13  reviews_list                 51717 non-null  str
 14  menu_item                    51717 non-null  str
 15  listed_in(type)              51717 non-null  str
 16  listed_in(city)              51717 non-null  str
dtypes: int64(1), str(16)
memory usage: 6.7 MB

In [5]:
data.shape

(51717, 17)

In [6]:
"""Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Cleaning individual columns.
Remove the NaN values from the dataset
Check for some more Transformations"""

'Deleting redundant columns.\nRenaming the columns.\nDropping duplicates.\nCleaning individual columns.\nRemove the NaN values from the dataset\nCheck for some more Transformations'

In [7]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='str')

In [8]:
columns_to_keep = ['name', 'online_order', 'book_table', 'rate','dish_liked','approx_cost(for two people)']
columns_to_drop = ['url', 'address','phone', 'location', 'rest_type', 'cuisines','reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)' ]

In [9]:
data[columns_to_keep]

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [10]:
modify_data = data[columns_to_keep]

In [11]:
modify_data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

# 2nd Way - Dropping columns

In [12]:
data.drop(columns= columns_to_drop, inplace= True)

In [13]:
data

,name,online_order,book_table,rate,votes,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Masala Dosa,300
4,Grand Village,No,No,3.8/5,166,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,0,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,13,NaN,"1,500"

# Renaming Columns

### renaming columns 1 by 1

In [14]:
data.rename(columns= {"name":"name1"})

,name1,online_order,book_table,rate,votes,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Masala Dosa,300
4,Grand Village,No,No,3.8/5,166,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,0,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,13,NaN,"1,500"

In [15]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'dish_liked',
       'approx_cost(for two people)'],
      dtype='str')

In [16]:
data.columns[0].capitalize()

'Name'

In [17]:
for i in data.columns:
    print(i.capitalize())

Name
Online_order
Book_table
Rate
Votes
Dish_liked
Approx_cost(for two people)

In [18]:
new_column_names =  []
for i in data.columns:
    new_column_names.append(i.capitalize())

In [19]:
data.columns = new_column_names

In [20]:
data.head()

,Name,Online_order,Book_table,Rate,Votes,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Masala Dosa,300
4,Grand Village,No,No,3.8/5,166,"Panipuri, Gol Gappe",600

# Dropping Duplicates

In [21]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
51712     True
51713     True
51714    False
51715     True
51716     True
Length: 51717, dtype: bool

In [22]:
data.duplicated().sum()

np.int64(29103)

In [23]:
data.duplicated().value_counts()

True     29103
False    22614
Name: count, dtype: int64

In [24]:
data.drop_duplicates(inplace = True)

In [25]:
data.duplicated().sum()

np.int64(0)

# Removing the NaN values

In [26]:
data.isna().sum()

Name                               0
Online_order                       0
Book_table                         0
Rate                            2420
Votes                              0
Dish_liked                     11348
Approx_cost(for two people)      141
dtype: int64

In [27]:
data.dropna(inplace= True)

In [28]:
data.isna().sum()

Name                           0
Online_order                   0
Book_table                     0
Rate                           0
Votes                          0
Dish_liked                     0
Approx_cost(for two people)    0
dtype: int64

In [29]:
data

,Name,Online_order,Book_table,Rate,Votes,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Masala Dosa,300
4,Grand Village,No,No,3.8/5,166,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
51615,Little Onnion,Yes,No,3.8 /5,134,"Vegetable Biryani, Dum Biryani, Kheer",500
51617,Breakfast House,No,No,3.6 /5,49,"Coffee, Vada, Mla Dosa",300
51620,Fujian Express,Yes,No,3.8 /5,182,"Noodles, Chicken Noodle, Momos, American Chops...",600
51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,411,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
51677,Bhagini,No,No,2.5 /5,81,"Biryani, Andhra Meal",800

In [30]:
data.reset_index(inplace = True)

In [31]:
data

,index,Name,Online_order,Book_table,Rate,Votes,Dish_liked,Approx_cost(for two people)
0,0,Jalsa,Yes,Yes,4.1/5,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,1,Spice Elephant,Yes,No,4.1/5,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,2,San Churro Cafe,Yes,No,3.8/5,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Masala Dosa,300
4,4,Grand Village,No,No,3.8/5,166,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...,...
11188,51615,Little Onnion,Yes,No,3.8 /5,134,"Vegetable Biryani, Dum Biryani, Kheer",500
11189,51617,Breakfast House,No,No,3.6 /5,49,"Coffee, Vada, Mla Dosa",300
11190,51620,Fujian Express,Yes,No,3.8 /5,182,"Noodles, Chicken Noodle, Momos, American Chops...",600
11191,51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,411,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
11192,51677,Bhagini,No,No,2.5 /5,81,"Biryani, Andhra Meal",800

In [32]:
data.drop(columns = "index", inplace= True)

In [33]:
data

,Name,Online_order,Book_table,Rate,Votes,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Masala Dosa,300
4,Grand Village,No,No,3.8/5,166,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
11188,Little Onnion,Yes,No,3.8 /5,134,"Vegetable Biryani, Dum Biryani, Kheer",500
11189,Breakfast House,No,No,3.6 /5,49,"Coffee, Vada, Mla Dosa",300
11190,Fujian Express,Yes,No,3.8 /5,182,"Noodles, Chicken Noodle, Momos, American Chops...",600
11191,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,411,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
11192,Bhagini,No,No,2.5 /5,81,"Biryani, Andhra Meal",800

# Cleaning Individual Columns

In [34]:
data["Rate"]

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
11188    3.8 /5
11189    3.6 /5
11190    3.8 /5
11191    4.2 /5
11192    2.5 /5
Name: Rate, Length: 11193, dtype: str

In [35]:
data["Rate"][10]

'4.2/5'

In [36]:
type(data["Rate"][10])

str

In [37]:
data["Rate"]= data["Rate"].str.replace(" ", "")

In [38]:
data["Rate"] = data["Rate"].str.replace("/", " out of ")

In [39]:
data

,Name,Online_order,Book_table,Rate,Votes,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1 out of 5,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1 out of 5,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8 out of 5,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7 out of 5,88,Masala Dosa,300
4,Grand Village,No,No,3.8 out of 5,166,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
11188,Little Onnion,Yes,No,3.8 out of 5,134,"Vegetable Biryani, Dum Biryani, Kheer",500
11189,Breakfast House,No,No,3.6 out of 5,49,"Coffee, Vada, Mla Dosa",300
11190,Fujian Express,Yes,No,3.8 out of 5,182,"Noodles, Chicken Noodle, Momos, American Chops...",600
11191,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 out of 5,411,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
11192,Bhagini,No,No,2.5 out of 5,81,"Biryani, Andhra Meal",800

In [40]:
data["Online_order"]

0        Yes
1        Yes
2        Yes
3         No
4         No
        ...
11188    Yes
11189     No
11190    Yes
11191     No
11192     No
Name: Online_order, Length: 11193, dtype: str

In [41]:
data["Online_order"] = data["Online_order"].map({"Yes": 1, "No": 0})

In [42]:
data

,Name,Online_order,Book_table,Rate,Votes,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1 out of 5,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1 out of 5,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8 out of 5,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7 out of 5,88,Masala Dosa,300
4,Grand Village,0,No,3.8 out of 5,166,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
11188,Little Onnion,1,No,3.8 out of 5,134,"Vegetable Biryani, Dum Biryani, Kheer",500
11189,Breakfast House,0,No,3.6 out of 5,49,"Coffee, Vada, Mla Dosa",300
11190,Fujian Express,1,No,3.8 out of 5,182,"Noodles, Chicken Noodle, Momos, American Chops...",600
11191,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 out of 5,411,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
11192,Bhagini,0,No,2.5 out of 5,81,"Biryani, Andhra Meal",800

In [43]:
data["Online_order"].value_counts()

Online_order
1    7822
0    3371
Name: count, dtype: int64

# Export to CSV

In [44]:
data.to_csv("Cleaned_data.csv")

In [45]:
pd.read_csv("Cleaned_data.csv")

,Unnamed: 0,Name,Online_order,Book_table,Rate,Votes,Dish_liked,Approx_cost(for two people)
0,0,Jalsa,1,Yes,4.1 out of 5,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,1,Spice Elephant,1,No,4.1 out of 5,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,2,San Churro Cafe,1,No,3.8 out of 5,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,3,Addhuri Udupi Bhojana,0,No,3.7 out of 5,88,Masala Dosa,300
4,4,Grand Village,0,No,3.8 out of 5,166,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...,...
11188,11188,Little Onnion,1,No,3.8 out of 5,134,"Vegetable Biryani, Dum Biryani, Kheer",500
11189,11189,Breakfast House,0,No,3.6 out of 5,49,"Coffee, Vada, Mla Dosa",300
11190,11190,Fujian Express,1,No,3.8 out of 5,182,"Noodles, Chicken Noodle, Momos, American Chops...",600
11191,11191,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 out of 5,411,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
11192,11192,Bhagini,0,No,2.5 out of 5,81,"Biryani, Andhra Meal",800

In [46]:
data.to_csv("Cleaned_data_without_index.csv", index = False )

In [47]:
pd.read_csv("Cleaned_data_without_index.csv")

,Name,Online_order,Book_table,Rate,Votes,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1 out of 5,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1 out of 5,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8 out of 5,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7 out of 5,88,Masala Dosa,300
4,Grand Village,0,No,3.8 out of 5,166,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
11188,Little Onnion,1,No,3.8 out of 5,134,"Vegetable Biryani, Dum Biryani, Kheer",500
11189,Breakfast House,0,No,3.6 out of 5,49,"Coffee, Vada, Mla Dosa",300
11190,Fujian Express,1,No,3.8 out of 5,182,"Noodles, Chicken Noodle, Momos, American Chops...",600
11191,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 out of 5,411,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
11192,Bhagini,0,No,2.5 out of 5,81,"Biryani, Andhra Meal",800